//
//  NPrintingQuestions.swift
//  QlikCheck
//
//  Created by Rohit Kanade on 28/10/17.
//  Copyright © 2017 QlikCheck. All rights reserved.
//

import Foundation


import Foundation

func NPrintingQuestions() -> [Questions] {
    
    var questions = [Questions]()
    
    // MARK: Questions
    
    
    let one = Questions()
    one.question = "Can multiple conditions be set to any report in NPrinting?"
    
    
    one.optionA = "Yes, it is possible"
    one.optionB = "Only one condition can be set per report"
    one.optionC = "No, only one condition can be set per report"
    one.optionD = "Yes, but max 3 conditions at a time"
    
    one.rightAnswer = "Yes, it is possible"
    
    one.explanation = "Multiple conditions can be set for any report generation"
    
    questions.append(one)
    
    // 2
    let two = Questions()
    two.question = "In order to distribute report using NPrinting after successful reload of .qvw file, to what should we set Nprinting service to?"
    
    two.optionA = "Set to accept Internal requests"
    two.optionB = "Set to accept External requests"
    two.optionC = "Set start type to Automatic"
    two.optionD = "Set NPrinting service to detect QDS service running"
    
    two.rightAnswer = "Set to accept External requests"
    
    two.explanation = "By setting Nprinting to external requests, it can read files such as XML"
    
    questions.append(two)
    
    // 3
    let three = Questions()
    three.question = "While using NPrinting email, can you attach external files which are not generated by NPrinting?"
    
    three.optionA = "No, we cannot at all"
    three.optionB = "No, only NPrinting generated files can be attached"
    three.optionC = "Yes only external PDF files can be attached"
    three.optionD = "Yes by checking 'Attach Report' box we can attach external files"
    
    three.rightAnswer = "Yes by checking 'Attach Report' box we can attach external files"
    
    three.explanation = "Yes it is possible."
    
    questions.append(three)
    
    // 4
    let four = Questions()
    four.question = "Does NPrinting work with Section Access?"
    
    four.optionA = "Yes works with only NT Security settings"
    four.optionB = "Yes by checking 'Enable Security' box it is possible"
    four.optionC = "No, it doesn't work with Section Access"
    four.optionD = "Qlik doesn't control security, so cannot."
    
    four.rightAnswer = "Yes by checking 'Enable Security' box it is possible"
    
    four.explanation = "Yes it is possible. "
    
    questions.append(four)
    
    // 5
    let five = Questions()
    five.question = "Your manager want to organize the reports to be distributed using NPrinting, is it possible to ZIP the reports?"
    
    five.optionA = "Yes works with only win-zip compression"
    five.optionB = "Yes NPrinting can be used to ZIP reports"
    five.optionC = "No, it doesn't work with Nprinting"
    five.optionD = "It depends on external services"
    
    five.rightAnswer = "Yes NPrinting can be used to ZIP reports"
    five.explanation = "Yes it is possible. "
    
    
    questions.append(five)
    
    
    
    //6
    let six = Questions()
    six.question = "Business users create lot of bookmarks, can the bookmarks be used to create filters in NPrinting?"
    
    six.optionA = "Yes, Home > Open Filters Window > Select the Bookmarks"
    six.optionB = "No this option is not available"
    six.optionC = "It can be directly controlled from Document Properties in the QVW files"
    six.optionD = "Bookmarks created in QVW is not accessible from Nprinting"
    
    six.rightAnswer = "Yes, Home > Open Filters Window > Select the Bookmarks"
    six.explanation = "There are number of choices to select bookmarks as filters"
    questions.append(six)
    
    
    //7
    let seven = Questions()
    seven.question = "Suppose you have to create Budget plans reports for year and country combinations, is it possible to create separate reports in Nprinting?"
    
    seven.optionA = "No, it is not possible"
    seven.optionB = "Separate reports is possible but not for combination of fields"
    seven.optionC = "Using Cycle features in NPrinting it is possible"
    seven.optionD = "Using Loop and Reduce in NPrinting, it is possible "
    
    seven.rightAnswer = "Using Cycle features in NPrinting it is possible"
    seven.explanation = "Cycle features will generate individual reports for each year and each country"
    questions.append(seven)
    
    
    //8
    let eight = Questions()
    eight.question = "Your users wants to see HTML reports embedded within the body of an email message is it doable in NPrinting?"
    
    
    eight.optionA = "No, it is not possible"
    eight.optionB = "Reports can be attached to an email, but not embed in body of the message"
    eight.optionC = "By using 'Embed_HTML Report with Table_html' tag it is possible"
    eight.optionD = "By using 'File_Name_HTML Report with Table_html' it is possible"
    
    eight.rightAnswer = "By using 'Embed_HTML Report with Table_html' tag it is possible"
    eight.explanation = "Using the Embed HTML report tag it is possible"
    questions.append(eight)
    
    
    //9
    let nine = Questions()
    nine.question = "Is it possible to add multiple slides in Nprinting?"
    
    nine.optionA = "No, it is not possible"
    nine.optionB = "All reports are collaged into one slide"
    nine.optionC = "Yes by specifying range of slides, pages can be cycled into multiple slides"
    nine.optionD = "By manually adding several pages into different slides it is possible"
    
    nine.rightAnswer = "Yes by specifying range of slides, pages can be cycled into multiple slides"
    nine.explanation = "Same as Correct Option"
    questions.append(nine)
    
    
    //10
    let ten = Questions()
    ten.question = "Can NPrinting fetch users list from LDAP Directory?"
    
    ten.optionA = "No, it can only fetch users list from Excel and databases"
    ten.optionB = "No, it can only fetch users list from CSV files"
    ten.optionC = "Yes by importing from Directory Services it can fetch users list from LDAP Directory"
    ten.optionD = "Yes only if Qlikview servers are clustered"
    
    ten.rightAnswer = "Yes by importing from Directory Services it can fetch users list from LDAP Directory"
    ten.explanation = "Same as Correct Option"
    questions.append(ten)
    
    //11
    let eleven = Questions()
    eleven.question = "Can NPrinting be used to generate reports and store them in dynamic folder path?"
    
    eleven.optionA = "No, only default NPrinting folder is available"
    eleven.optionB = "Only subfolder of recipients is allowed"
    eleven.optionC = "Yes, Custom Path can be set in Nprinting"
    eleven.optionD = "Yes folder of recipients is allowed"
    
    eleven.rightAnswer = "Yes, Custom Path can be set in Nprinting"
    eleven.explanation = "From the custom folder type drop down we can choose Custom Path"
    questions.append(eleven)
    
    //12
    let twel = Questions()
    twel.question = "Now that dynamic folder path can be set can also we set dynamic names to the reports? "
    
    twel.optionA = "No, only default NPrinting report is possible"
    twel.optionB = "No, NPrinting only allows numeric file names"
    twel.optionC = "Yes, but only 20 maximum characters allowed as file name"
    twel.optionD = "Yes by checking 'Enable Dynamic Naming' box it is possible"
    
    twel.rightAnswer = "Yes by checking 'Enable Dynamic Naming' box it is possible"
    twel.explanation = "By checking 'Enable Dynamic Naming' box and then using Custom Dynamic Naming"
    questions.append(twel)
    
    //13
    let thirteen = Questions()
    thirteen.question = "How would you add CC or BCC while distributing reports via emails?"
    
    thirteen.optionA = "No, users usually receive the email and then they forward the reports"
    thirteen.optionB = "No, It is not allowed in NPrinting because of license cost"
    thirteen.optionC = "From File > Options > Email Settings > in Carbon Copy section add comma or semi-colon separated email ids"
    thirteen.optionD = "From Email Tab > Email Settings > in Extra Recipient section add comma or semi-colon separated email ids"
    
    thirteen.rightAnswer = "From File > Options > Email Settings > in Carbon Copy section add comma or semi-colon separated email ids"
    thirteen.explanation = "Same as Correct Option"
    questions.append(thirteen)
    
    //14
    let fourteen = Questions()
    fourteen.question = "In NPrinting can you schedule automatic jobs?"
    
    fourteen.optionA = "Yes, Select Schedules from left/upper panel, then create a new schedule"
    fourteen.optionB = "No, It is not allowed in NPrinting because of license cost"
    fourteen.optionC = "Only Weekly schedules are allowed"
    fourteen.optionD = "Only Monthly schedules are allowed"
    
    fourteen.rightAnswer = "Yes, Select Schedules from left/upper panel, then create a new schedule"
    fourteen.explanation = "Same as Correct Option"
    questions.append(fourteen)
    
    
    //15
    let fixteen = Questions()
    fixteen.question = "In NPrinting how to remove on-open password for reports?"
    
    fixteen.optionA = "Extra license needs to be purchased for this functionality"
    fixteen.optionB = "In 'Report Security' section > Keep 'Password to open' space as blank"
    fixteen.optionC = "No it is not possible"
    fixteen.optionD = "It is very complex to implement"
    
    fixteen.rightAnswer = "In 'Report Security' section > Keep 'Password to open' space as blank"
    fixteen.explanation = "Same as Correct Option"
    questions.append(fixteen)
    
        
    //--------
    
    return questions
    
}
